version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 20
    commands:
      - npm i -g yarn
      - yarn
  build:
    commands:
      - sam build
      - sam deploy --no-confirm-changeset
