AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  healthcare-ms

  Basic backend service as healthcare-ms

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  HealthcareApiGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,POST,GET,PATCH,PUT,DELETE'"
        AllowHeaders: "'Content-Type, Access-Control-Allow-Origin, Authorization'"

  HealthcareUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: healhcare-user
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  TaskManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HealthcareUserTable
      Events:
        PostUser:
          Type: Api
          Properties:
            RestApiId: !Ref HealthcareApiGw
            Path: /users
            Method: post
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref HealthcareApiGw
            Path: /users/{id}
            Method: get
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref HealthcareApiGw
            Path: /users/{id}
            Method: put
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref HealthcareApiGw
            Path: /users/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/app.ts

Outputs:
  HealthcareApiGw:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${HealthcareApiGw}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
